language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - npm run db
  - psql -U postgres -c "create extension fuzzystrmatch"
env:
  - DB_NAME=ihl_test
  - DB_USERNAME=postgres
  - DB_PASSWORD=""
  - DB_PASSWORD=127.0.0.1
  - COMMAND_PREFIX=!
  - OWNER_DISCORD_ID=76864899866697728
  - CLIENT_ID=360034352853155840
  - CALLBACK_URL=http://127.0.0.1:3000/callback
  - LOGGER_SILENT=true
  - LOGGER_LEVEL=debug
  - LOGGER_EXCEPTIONLOGFILE=exceptions.log
  - LOGGER_DIRNAME=logs
  - LOGGER_FILENAME=application-%DATE%.log
  - LOGGER_DATEPATTERN=YYYY-MM-DD-HH
  - LOGGER_ZIPPEDARCHIVE=true
  - LOGGER_MAXSIZE=20m
  - LOGGER_MAXFILES=14d